# Generated by Django 5.1.3 on 2024-12-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Ukraine', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
    ]
